In [1]:
import warnings
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split,cross_val_score,GridSearchCV 
from sklearn.metrics import confusion_matrix, accuracy_score,mean_squared_error,r2_score,classification_report
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB

In [2]:
warnings.filterwarnings("ignore")

In [3]:
data = pd.read_csv("data/golf.csv")

In [4]:
for i in data.columns:
  print(i,data[i].nunique())

Outlook 3
Temp 3
Humidity 2
Windy 2
Play Golf 2

In [5]:
data

     Outlook  Temp Humidity  Windy Play Golf
0      Rainy   Hot     High  False        No
1      Rainy   Hot     High   True        No
2   Overcast   Hot     High  False       Yes
3      Sunny  Mild     High  False       Yes
4      Sunny  Cool   Normal  False       Yes
5      Sunny  Cool   Normal   True        No
6   Overcast  Cool   Normal   True       Yes
7      Rainy  Mild     High  False        No
8      Rainy  Cool   Normal  False       Yes
9      Sunny  Mild   Normal  False       Yes
10     Rainy  Mild   Normal   True       Yes
11  Overcast  Mild     High   True       Yes
12  Overcast   Hot   Normal  False       Yes
13     Sunny  Mild     High   True        No
14     Rainy   Hot     High  False        No
15     Rainy   Hot     High   True        No
16  Overcast   Hot     High  False       Yes
17     Sunny  Mild     High  False       Yes
18     Sunny  Cool   Normal  False       Yes
19     Sunny  Cool   Normal   True        No
20  Overcast  Cool   Normal   True       Yes
21     Rainy  Mild     High  False        No
22     Rainy  Cool   Normal  False       Yes
23     Sunny  Mild   Normal  False       Yes
24     Rainy  Mild   Normal   True       Yes
25  Overcast  Mild     High   True       Yes
26  Overcast   Hot   Normal  False       Yes
27     Sunny  Mild     High   True        No
28     Rainy   Hot     High  False        No
29     Rainy   Hot     High   True        No
30  Overcast   Hot     High  False       Yes
31     Sunny  Mild     High  False       Yes
32     Sunny  Cool   Normal  False       Yes
33     Sunny  Cool   Normal   True        No
34  Overcast  Cool   Normal   True       Yes
35     Rainy  Mild     High  False        No
36     Rainy  Cool   Normal  False       Yes
37     Sunny  Mild   Normal  False       Yes
38     Rainy  Mild   Normal   True       Yes
39  Overcast  Mild     High   True       Yes
40  Overcast   Hot   Normal  False       Yes
41     Sunny  Mild     High   True        No

In [6]:
le=preprocessing.LabelEncoder()
for x in data:
    data[x]=le.fit_transform(data[x])

In [7]:
data

    Outlook  Temp  Humidity  Windy  Play Golf
0         1     1         0      0          0
1         1     1         0      1          0
2         0     1         0      0          1
3         2     2         0      0          1
4         2     0         1      0          1
5         2     0         1      1          0
6         0     0         1      1          1
7         1     2         0      0          0
8         1     0         1      0          1
9         2     2         1      0          1
10        1     2         1      1          1
11        0     2         0      1          1
12        0     1         1      0          1
13        2     2         0      1          0
14        1     1         0      0          0
15        1     1         0      1          0
16        0     1         0      0          1
17        2     2         0      0          1
18        2     0         1      0          1
19        2     0         1      1          0
20        0     0         1      1          1
21        1     2         0      0          0
22        1     0         1      0          1
23        2     2         1      0          1
24        1     2         1      1          1
25        0     2         0      1          1
26        0     1         1      0          1
27        2     2         0      1          0
28        1     1         0      0          0
29        1     1         0      1          0
30        0     1         0      0          1
31        2     2         0      0          1
32        2     0         1      0          1
33        2     0         1      1          0
34        0     0         1      1          1
35        1     2         0      0          0
36        1     0         1      0          1
37        2     2         1      0          1
38        1     2         1      1          1
39        0     2         0      1          1
40        0     1         1      0          1
41        2     2         0      1          0

In [8]:
data.shape

(42, 5)

In [9]:
data.dtypes

Outlook      int64
Temp         int64
Humidity     int64
Windy        int64
Play Golf    int64
dtype: object

In [10]:
data.isna().sum()

Outlook      0
Temp         0
Humidity     0
Windy        0
Play Golf    0
dtype: int64

In [11]:
numcols=data.dtypes[(data.dtypes=='float64')].index

In [12]:
for x in numcols:
    sns.boxplot(data[x])
    plt.show()

In [14]:
X=data.drop(['Play Golf'],axis=1)
y=data['Play Golf']

In [15]:
X.shape,y.shape

((42, 4), (42,))

In [16]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=.20,random_state=42)

In [17]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((33, 4), (9, 4), (33,), (9,))

In [18]:
naive_classifier = GaussianNB()

In [19]:
naive_classifier.fit(X_train,y_train)

GaussianNB()

In [20]:
y_pred=naive_classifier.predict(X_test)
y_pred

array([1, 0, 1, 1, 1, 1, 1, 0, 1])

In [21]:
y_test

25    1
13    0
8     1
26    1
4     1
39    1
19    0
29    0
30    1
Name: Play Golf, dtype: int64

In [22]:
confusion_matrix(y_test,y_pred)

array([[2, 1],
       [0, 6]])

In [23]:
accuracy_score(y_test,y_pred)*100

88.88888888888889